# Cores da Câmara dos Deputados (Manual de Identidade Visual)
[theme]
primaryColor = "#154453"
backgroundColor = "#D8E4E8"
secondaryBackgroundColor = "#CCDCE0"
textColor = "#262730"
font = "sans serif"
